version: '3.8'

services:

  # MongoDB - one shared instance with 3 databases
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - restaurant-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - menu-service
      - order-service
    networks:
      - restaurant-network

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/userDB
    depends_on:
      - mongodb
    networks:
      - restaurant-network

  # Menu Service
  menu-service:
    build: ./menu-service
    container_name: menu-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/menuDB
    depends_on:
      - mongodb
    networks:
      - restaurant-network

  # Order Service
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/orderDB
    depends_on:
      - mongodb
    networks:
      - restaurant-network

  # Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - restaurant-network

volumes:
  mongo-data:

networks:
  restaurant-network:
    driver: bridge
